### PR TITLE
Add total item test

### LINKED ISSUE #3: [3pt]  - Add tests for items counter - Student A
Make sure that function for the items counter is covered with unit tests using Jest.

### PR DESCRIPTION
**Pull request by micheaol**
## In this Pull request:

- Add unit tests for the items counter with Jest.

### CODE REVIEW

**Review by nicupop729 — CHANGES_REQUESTED** [review]
Good job, Michael!! :dart: :confetti_ball: 

Mock tests works!

You had done a fabulous job these days!!
Still, I cannot give you approval until I see that you resolved the conflicts and that you pass all linter checks with green!

**Comment by nicupop729** [comment]
**Please take extra care when resolving the conflicts!!**

**Comment by micheaol** [comment]
> Good job, Michael!! 🎯 🎊
> 
> Mock tests works!
> 
> You had done a fabulous job these days!! Still, I cannot give you approval until I see that you resolved the conflicts and that you pass all linter checks with green!

Resolved.

**Review by nicupop729 — APPROVED** [review]
Ok, great job!! :100: :dart

Fell free to merge :dancers:

**Pull request merged**
